POST http://localhost:3001/api/v1/user/newuser
content-type: application/json

{
    "userName": "ala",
    "email": "test@gmail.com",
    "hashedPassword": "testpassword123"
}

###

POST http://localhost:3001/api/v1/auth/login
content-type: application/json

{
    "email": "test@gmail.com",
    "hashedPassword": "testpassword123"
}