Get http://localhost:3001/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIyYzRhZDFjLWIzMDgtNGY4ZS1iMjgzLWQzZTA3NTNmOWY3ZCIsInVzZXJOYW1lIjoiYWxhIiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImhhc2hlZFBhc3N3b3JkIjoiJDJiJDEwJDVKL0NYN1JBSU04TXZoYUZxNXNaMXV0b0lTWEV2YWkuTXRRSXZSMUFGR2pocllvM250dS8yIiwiY3JlYXRlZEF0IjoiMjAyMi0wOC0wNlQxNDo1MTozOS4wNTlaIiwidXBkYXRlZEF0IjoiMjAyMi0wOC0wNlQxNDo1MTozOS4wNTlaIiwiaWF0IjoxNjU5Nzk3NTAyfQ.dC8xR8PODWdHd3SoZMCZ42051UPHaJB4dhF3fdiJbVc