PUT http://localhost:3001/api/v1/beach/updatebeach/22226871-8548-4daa-b571-1537bd4b7122
content-type: application/json

{
    "name": "bizerte",
    "governorate": "bizerte",
    "latitude": 3.19,
    "longitude": 25.65
}
