POST http://localhost:3001/api/v1/beach/newbeach 
content-type: application/json

{
      "name": "Maamoura Beach",
      "governorate": "Nabeul",
      "latitude": 36.4634,
      "longitude": 10.8120
}