PUT http://localhost:3001/api/v1/beach/updatebeach/e8628f2d-0858-4d94-8a5f-92647fc71858
content-type: application/json

{
    "imagepath": "/home/aladin/Ca-Baigne/Backend/uploads/beaches/image-mamoura.jpg"
}
