name: Deployment

on:
  workflow_run:
    workflows: ["Cabaigne Backend API integration"]
    types:
      - completed

jobs:
  deployment:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: pull changes
        run: |
            cd /home/azureuser/Ca-Baigne
            git pull 
            sudo docker-compose up --build -d
