name: Cabaigne backend API Continuous Integration

on: 
  # change to pull_request later
  push:
    branches: [ main ]

jobs:
  setup_postgres_database:
    runs-on: ubuntu-latest
    container: node:latest

  services:
    postgres:
      image: postgres:latest
      env:
        POSTGRES_DB: postgres_db
        POSTGRES_PASSWORD: postgres_password
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres_user
      ports:
        - 5432:5432
      options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  steps:
    - name: Install PostgreSQL client
      run: |
          apt-get update
          apt-get install --yes postgresql-client
  steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: setup the project database from file
      run: psql -f setup_database.sql
