name: Cabaigne Backend API integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  setup_postgres_database-job:
    name: Setup_database
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Check out code code in the repo
      uses: actions/checkout@v2

    - name: Run migrations
      run: psql -f setup_database.sql postgresql://postgres:postgres@localhost:5432/postgres
    - name: install node modules
      run: |
        cd Backend/
        npm ci
