name: Cabaigne backend API Continuous Integration

on: 
  # change to pull_request later
  push:
    branches: [ main ]

jobs:
  setup_postgres_database-job:
    runs-on: ubuntu-latest
    container: node:latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres_password
        ports:
          - postgres:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run migrations
        run: psql -f setup_database.sql postgresql://postgres:postgres@localhost:5432/postgres
